[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "c8f8884386cc49365813a44300a0bda1a3bbe648"
os = "macos"

    [[SLEEF.download]]
    sha256 = "a8456083752b34f849bfe1cd351d19b4636dac74073372563823030928795dcd"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.aarch64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "9c6ec6a774d4a5812d845866d89c2ed8445ad8bc"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "8fca5b6bb95af030ba9641e61910a1e1ae8882dd24e160816f609bea15999d27"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.aarch64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "20e125cd44197a5c090c75643accd14ba3e6a34d"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "6901444e5ef6ec921b1991aa218d615a52b851d56c765df24f1b5f4c2b28824e"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.aarch64-linux-musl.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "206071e812b9c7e534488149234963a66be967a0"
os = "freebsd"

    [[SLEEF.download]]
    sha256 = "b1fbafb92b109dc0ab9915e48eac17fae8cf3d501db71d68d83d81b1c6273de5"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.aarch64-unknown-freebsd.tar.gz"
[[SLEEF]]
arch = "powerpc64le"
git-tree-sha1 = "102965c0e5196007fe0e32845cd74cae296c0d67"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "74c93f05aedd66ff9b56c4b755ce51d4066475e0768826f897fb4676066bd70b"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.powerpc64le-linux-gnu.tar.gz"
[[SLEEF]]
arch = "riscv64"
git-tree-sha1 = "0986d6bbcfd1bc7e7d54930449590db23f9aecec"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "63d556db822986e27b13a878503669afc90630c758d1d134f190d2177d4c488e"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.riscv64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "d3312f75f62e5d315e77bcd9eb1f0525b50f31ce"
os = "macos"

    [[SLEEF.download]]
    sha256 = "64f0e5f7fd451db8736a7a16282a22830aa295d3990c50e097557d3bae32ba15"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.x86_64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "da0e064ab6bc89835082e4314c9646afff56d46d"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "4ea212dcbbed57cb014931b83e8cecb5c1ec43849a21a17fcdc3aaf43ab5c50a"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.x86_64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "e254901333426dcaafcfec15a8e786045f232562"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "7043229f8953580fb51e8fd15cc85b3f0c9b66f709c8e4f5fdd6c5aa3802b1d1"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.x86_64-linux-musl.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "151ab66a5cccd0cdf6e7a52be4239871713a90b6"
os = "freebsd"

    [[SLEEF.download]]
    sha256 = "8a3120502d11a38947ebc00aa69164ed470bac3178dfbb6d417a71f6c0dd460b"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.9.0+0/SLEEF.v3.9.0.x86_64-unknown-freebsd.tar.gz"
