[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "aa399b3ee38a57c6af4fc4335f0704c74a6d3010"
os = "macos"

    [[SLEEF.download]]
    sha256 = "c852825b8044e0859f0033159e4fc3730bf00c3142732f3bbaf2fcf0f5e9a82a"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.aarch64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "a35815a710af31b3845db4e35bb4b18d5cb52737"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "779ebf0f302868880b2a4780fb7a85e8c7da64820545c24fe15973d727139566"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.aarch64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "9051489fcc3f87dfe6ada96a94efe66bcc6dd5ec"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "f0552a21363f336a29d0ce972bcf97d91032caf3a03b9caf438cadc56eb6946c"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.aarch64-linux-musl.tar.gz"
[[SLEEF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e0e88138f8654eaf50032b52b0dc226f5f3521d"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "ad8102cf3608ee949fa5329a1a9eec58efd1bd57db83feb66b7ed556798b896c"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.armv6l-linux-gnueabihf.tar.gz"
[[SLEEF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47641d981dcd14b9a1ed3a210e9481fe3b78881d"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "90ece7b3e8cb6c51d97d3bc197dc4f6d372431e13febc285d9f78f661cbfa5ee"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.armv6l-linux-musleabihf.tar.gz"
[[SLEEF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07fb5b59aedf26f6e851beb57fb44afcd3c84e9e"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "6d0949cf9246481f10d4c2b7c14fe61ffa83f99891be571f7b0045869f3765c9"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SLEEF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "037afa05a551ef07cfb7b26ae88fcef147fc361d"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "28692b01f06b2dcf76e5c10aedbb3264b03cacadc68ddc2f38b71f89c2531f5b"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.armv7l-linux-musleabihf.tar.gz"
[[SLEEF]]
arch = "i686"
git-tree-sha1 = "b6e0493d963287b534f5549c8e05b75570f637d6"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "9bc989e9827f14897db9ff1f0e6d5b00a22f0d92f2174bd296b750f49d64a87e"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.i686-linux-gnu.tar.gz"
[[SLEEF]]
arch = "i686"
git-tree-sha1 = "84d93c58daaf26f437b0194ffafddbb7b6372fa6"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "78109b0be794f5f0c15a6c7de6a1fdae5a5a4d1e3ea48d411a2e3395f419fe57"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.i686-linux-musl.tar.gz"
[[SLEEF]]
arch = "powerpc64le"
git-tree-sha1 = "acee4fd7652b8a094e13fece4b878b427201dee2"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "43c7805f1ab819e83ac1bf00b24de8a0027e03a280e2e8bdc77b0a4693290cb1"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.powerpc64le-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "f06e3a3afc17ab0ef957e7ab606fe312957d9f91"
os = "macos"

    [[SLEEF.download]]
    sha256 = "d2e8469093b2e65aa875bbc2f0be0af6d3f3c6f940fbaa607758fe19545220bd"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.x86_64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "497197892a04efe74e7a50a4a5ab47a130899e7a"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "04b8fdf954af3ba7e4a42839e99b923ff71e82a63ad9aaf35f8cc79137ab9523"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.x86_64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "abe264e2c27fe62f45ab3585044feb3729a34253"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "d90abf382b9964699b6661707eb2609de01a676eac70de89852f8ba066846850"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.x86_64-linux-musl.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "5d3cd814edfc7af0310c47a9fc1e76516b1fc029"
os = "freebsd"

    [[SLEEF.download]]
    sha256 = "52cc9559647d5a66a7ff7c4a2903dd369831a3f9e249f94387259c3b70b959b5"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.x86_64-unknown-freebsd.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "13107622830c975aa0fc6cd1c3df9cb5e3e960a9"
os = "windows"

    [[SLEEF.download]]
    sha256 = "31be4338710549c7c12a58f5738723f2efdd1ddc5e8e4fe66efd24b305d45a4b"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.4.1+0/SLEEF.v3.4.1.x86_64-w64-mingw32.tar.gz"
