[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "381cbb44c5a02b269ee93e369cb7b8fec22f12ec"
os = "macos"

    [[SLEEF.download]]
    sha256 = "4afe0c6d8472f0832332b6a53c183d969f33936a1870762ae5c8676167cb328b"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.aarch64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "84600d40201a4ef4fcc8c735fe8c49f016cbf89f"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "3e090e7268a5be9a3c971cc9d8e7e923d09d630daf44795f65ee525ed0ad4f46"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.aarch64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "aarch64"
git-tree-sha1 = "a2d0da3e6831d644570c605d040c2d18c2c010cb"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "ff8efd4e0257fe987fcc548945401fbb2aad13cdd9916c3e342df41f6f80447c"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.aarch64-linux-musl.tar.gz"
[[SLEEF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0331805c1096c9b04195deef5d7966952876e2d9"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "b47c9b22597ee3b09b404338971ee3ed77cfb64f3462f4c29122e22672a7b9bc"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.armv6l-linux-gnueabihf.tar.gz"
[[SLEEF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9bd77ead5454183956aab1009a09887d2456ea9f"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "bccfc737233f07a9f6c2c23e23297a734653b41d1dcacd5506e4cb1a08931454"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.armv6l-linux-musleabihf.tar.gz"
[[SLEEF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18b7e52caef58f5f76ae7b1011a0266bf2c7752c"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "1d6c84a9bbde5dd1df45654364b54695daa67ae02360b596ce5c0b1dbfda1be1"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.armv7l-linux-gnueabihf.tar.gz"
[[SLEEF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db0b0a4efd2d6a682c39451b494590e6e96756cf"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "00078ca4e7873e49a47a1fed258841bb33e868604d89042510aac3f18006d536"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.armv7l-linux-musleabihf.tar.gz"
[[SLEEF]]
arch = "i686"
git-tree-sha1 = "9e28ecdd49d579ccc656001f30d343af2685efbb"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "e121313e987f75400d76ef433d5c45f2100735ecae08d930b9eacb2d3eb0c245"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.i686-linux-gnu.tar.gz"
[[SLEEF]]
arch = "i686"
git-tree-sha1 = "e50797958d35d54830392c813140d00f39c29700"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "e18e906144523c7c21b6e4c6e8c9af06322a26ee7d07d8757453dd558da82d2c"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.i686-linux-musl.tar.gz"
[[SLEEF]]
arch = "powerpc64le"
git-tree-sha1 = "8f79d6c841f6c036e5b298a0f2ce9093d1a3a916"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "965f89e65a3c731dcba64ae0d8c373055e2cc0d6df5c3a6bebeed3341476917d"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.powerpc64le-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "62adee8dedfb92ad22bea9da51d2881badc3e5c0"
os = "macos"

    [[SLEEF.download]]
    sha256 = "8188243571242540be3bca7ccaa2f786d8e5046684e46fe6f0c6c7c2fa7528ec"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.x86_64-apple-darwin.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "db73f607dc5c9362b3d543c64267d012ea2eeba0"
libc = "glibc"
os = "linux"

    [[SLEEF.download]]
    sha256 = "d1a994ad1bb87b4bdfb2b37c5b6cced7b2a1270b42b0bb7fad9bbf6370872291"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.x86_64-linux-gnu.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "9231dfab4893900cf7e92fc789231b8023b9bdc9"
libc = "musl"
os = "linux"

    [[SLEEF.download]]
    sha256 = "6429265f3199e80f2c02f2fab5882e8e31bbf4f3b8a0824e81f5a171f9525cad"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.x86_64-linux-musl.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "5895170658001be7e8c6b4124378ba0ae68460d0"
os = "freebsd"

    [[SLEEF.download]]
    sha256 = "c414d54301719620a34abe52179e1943108bc5ff14c473107b9151b7a5d2c9d0"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.x86_64-unknown-freebsd.tar.gz"
[[SLEEF]]
arch = "x86_64"
git-tree-sha1 = "fa970b0a8b4bd2f8ea0112719412067ef1d03d9f"
os = "windows"

    [[SLEEF.download]]
    sha256 = "ecaf1899e8016abc02bb790d950b60db6bfec5dc2adceca3dc3e93055b6b04f7"
    url = "https://github.com/JuliaBinaryWrappers/SLEEF_jll.jl/releases/download/SLEEF-v3.5.2+0/SLEEF.v3.5.2.x86_64-w64-mingw32.tar.gz"
