# Autogenerated wrapper script for SLEEF_jll for x86_64-w64-mingw32
export libsleef, libsleefdft, libsleefquad, libsleefscalar

using CompilerSupportLibraries_jll
using MPFR_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("SLEEF")
JLLWrappers.@declare_library_product(libsleef, "libsleef.dll")
JLLWrappers.@declare_library_product(libsleefdft, "libsleefdft.dll")
JLLWrappers.@declare_library_product(libsleefquad, "libsleefquad.dll")
JLLWrappers.@declare_library_product(libsleefscalar, "libsleefscalar.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPFR_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libsleef,
        "bin\\libsleef.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsleefdft,
        "bin\\libsleefdft.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsleefquad,
        "bin\\libsleefquad.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsleefscalar,
        "bin\\libsleefscalar.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
